### ISSUE TITLE
taxon reactions: Simultaneous reactions add both user & place

### ISSUE THREAD

**Issue by michaelpirrello** [synrg/dronefly#101]
![image](https://user-images.githubusercontent.com/63756824/83572448-9ad8d380-a4f7-11ea-8642-1d8698545cf3.png)

**Comment by synrg** [comment]
As per issue title, if you press both :hash: and :house: reaction very close together in time on an embed with no user or place stats on it yet, then there is a race condition, and both the user and place get added together. That is not what is supposed to happen.

The desired behaviour is the first reaction takes out a lock so that no other reactions can be processed, and then it updates the embed, and then it releases the lock only when it can be confirmed the embed has been updated. This is because the embed itself is considered the authority for whether it is in one mode vs. another.

There is existing locking code that attempts to guarantee this behaviour, but apparently it has holes in it, probably due to some wrong assumption I've made about the states of the various entities in play.

Therefore, since we have a reproducible test case, a good place to start with debugging this would be to have the code log all of the various state information that changes during the whole lock-read-update-unlock sequence while reproducing the issue with 2 simultaneous reactions on the same embed, one for the user stats and the other for the place stats.

**Comment by synrg** [comment]
I think this should work:

- user presses any of the four buttons that update the user / place counts
- take out a `reaction_lock[msg.id]` *immediately*
- cached get of embed, keyed by `msg.id`:
  - impl with `@functools.lru_cache()` and some reasonable max size (1000?)
  - fetch the message from discord
  - instantiate an INatEmbed from its first embed
  - cache the resulting embed
- depending on kind of button and kind of embed:
  - embed doesn't have a kind (user or place) yet? *set the kind, according to which button was pressed*
  - embed is the wrong kind for the button pressed? *ignore the button press*
  - embed is the right kind for the button pressed? (always true if it didn't have a kind yet)
    - if button was :hash: or :home: then proceed ...
    - if button was :pencil: or :round_pushpin: this is going to take a while, so take out a `predicate_lock[msg.id]` and release the `reaction_lock` (there can only be one active predicate query at a time)
      - when the user finally answers, take out a new `reaction_lock[msg.id]` and proceed ...
    - finally, update the cached embed, then do a `msg.edit()` to actually update it in the channel
- release the `reaction_lock`

This should prevent two simultaneous button presses from both seeing the embed as "empty" and therefore both try to add opposite types of content at once (user *and* place). the whole sequence from initial button press to eventually writing out the new embed is locked. because the final step is to update the cached embed, if there's another button press queued up immediately afterwards then the embed is guaranteed to be in the cache (i.e. the latency between the `msg.edit()` call and the re-fetch of the message from the channel has been eliminated, which is at the root of the bug).

**Comment by synrg** [comment]
Fixed a different way in 7c8453e0678084c3ca1b31d9297c43cba89a4514
