### ISSUE TITLE
place: set place for native/introduced queries

### ISSUE THREAD

**Issue by michaelpirrello** [synrg/dronefly#111]
On iNat, the "Name Place"
![image](https://user-images.githubusercontent.com/63756824/87152957-a9e43b80-c284-11ea-9124-a963dc08d251.png)
is used to control observation and taxon page displays regarding native/non-native status
![image](https://user-images.githubusercontent.com/63756824/87153048-ced8ae80-c284-11ea-8197-80394356136c.png)
![image](https://user-images.githubusercontent.com/63756824/87153091-e31cab80-c284-11ea-94c8-6c3b22ce1248.png)

I would like to be able to utilize the bot to look at statistics regarding the percentage of a user's observations (e.g. mine) that are endemic, native, introduced, invasive, etc.
similar to what iNat describes in the old API:
![image](https://user-images.githubusercontent.com/63756824/87153214-1bbc8500-c285-11ea-807b-ff01fe73109b.png)

As discussed, this may require the user to set a Name Place (that could differ from Home Place). Lacking that, there might be a fall back hierarchy of Name Place, else Home Place, else Server Default (as set by Server Administrator)

**Comment by synrg** [comment]
I find it strange that a setting they describe as "Prioritize common names used in this place" is used for something entirely different. Let's assume, for the moment, it's just misdescribed and they will never disentangle the two concepts ...

In the API, this is what preferred_place_id refers to. So if you say for my province (6853 = Nova Scotia, CA):

https://api.inaturalist.org/v1/taxa/77776?preferred_place_id=6853

Then you get back a result that has

```json
...
            "preferred_common_name": "Balkan toadflax",
            "establishment_means": {
                "establishment_means": "introduced",
                "id": 5650134,
                "place": {
                    "id": 6853,
                    "name": "Nova Scotia",
                    "display_name": "Nova Scotia, CA",
                    "ancestry": "97394/6712"
                }
            },
            "preferred_establishment_means": "introduced",
...
```

Now, I wonder if we really want a separate setting for this. If all these concepts are tied together: a person's default place, their preferred name place, and the preferred place for establishment means, maybe that all fits under the umbrella of `,set user home` as we have it right now? Thus:

- if a person has a home place set, and they type `,t linaria dalmatica` then it should show establishment means for their home place, indicated by :exclamation: in the icons, and the common name should be their own preferred common name, and the next line of the embed should indicate:

> :exclamation: Introduced in Nova Scotia, CA (Source List: **Nova Scotia Check List**)

where the **Nova Scotia Check List** link should link to `https://www.inaturalist.org/listed_taxa/5650134`

- if another person has a home place set, and they press :house: then when their place is added to the table, it should include:

> **#** :exclamation: Nova Scotia, CA

No link to the "introduced" status is provided here because that takes up space needlessly in the embed. If they want the link, they can do `,last t` and it will show the embed again, only with their own home place providing the context to show its status.

**Comment by synrg** [comment]
> As discussed, this may require the user to set a Name Place (that could differ from Home Place). Lacking that, there might be a fall back hierarchy of Name Place, else Home Place, else Server Default (as set by Server Administrator)

Although as stated in my previous comment, I think we just want to stick with a "home place" for now, as it integrates nicely with the place support we've written so far. I do like the idea of a server default set by the server admins, so I'll create a separate issue now to deal with that.

**Comment by synrg** [comment]
I have started work on this. As of cbabad4dafb9398513eb74b6dae7bd4679a77954 there is some rudimentary support for querying taxon means for a place. It's fussy, though. It requires the taxon id# be looked up, not the name (because so far I'm only using `listed_taxa` from the full record). It will not remain like this. This was for demonstration purposes only. Also, the formatting of the output will be quite different, and it probably won't be a subcommand. I have it as `,taxon means` but that's just for simplicity/convenience of development. It should be integrated into `,taxon` and `,obs` output. It does not yet understand place hierarchies, either. It currently requires that the place given is the exact place where there is a listing for the species (e.g. if you specified a county and it is only listed for the state, there will be *no* output). The formatting of the message that is output is deficient in a number of regards (doesn't mention the display name of the place, nor establishment means label itself, but just links to the listing, and doesn't include any emoji like on the web to signify introduced vs native).

**Comment by synrg** [comment]
p.s. because the work in progress is on establishmeant-means branch and not master, it is available for testing currently only on CuckooBee, which is not always running. I'll leave it running today so people can play with it, though. See my comments today on #bot-stuff on iNaturalist Discord & #bot-testing on Dronefly Discord.

**Comment by synrg** [comment]
This is already delivered both for observations & taxon. Establishment Means and Conservation Status are shown.
